version: '3.8'
services:
  db:
    image: mariadb:10.9
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
  app:
    build: .
    command: npm run test:integration
    environment:
      NODE_ENV: test
      DB_DIALECT: mariadb
      DB_HOST: db
      DB_NAME: testdb
      DB_USER: test
      DB_PASS: test
      # Esto asume que tu db.js lee estas variables
    depends_on:
      - db
